# name: Pinterest Pin Generation
# on:
#   workflow_dispatch:
#     inputs:
#       force_run:
#         description: 'Force run even if no new URLs'
#         required: false
#         default: 'false'
#         type: choice
#         options:
#           - 'true'
#           - 'false'
#       workflow_enabled:
#         description: 'Enable or disable the workflow'
#         required: false
#         default: 'enabled'
#         type: choice
#         options:
#           - 'enabled'
#           - 'disabled'
#   schedule:
#     - cron: '0 */2 * * *'  # Run every 2 hours
# jobs:
#   process-urls:
#     runs-on: ubuntu-latest
#     # Skip the job if workflow is disabled, unless manually triggered
#     if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.event.inputs.workflow_enabled != 'disabled') }}
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 1
#           token: ${{ secrets.GITHUB_TOKEN }}
          
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'
          
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pandas pillow google-genai pyyaml requests
          
#       - name: Process URLs
#         id: process_urls
#         env:
#           GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
#           CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
#           CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
#           CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
#           CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
#           EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
#         run: |
#           python .github/scripts/process_urls.py
#         continue-on-error: false
        
#       - name: Commit changes
#         run: |
#           git config --global user.name 'GitHub Action'
#           git config --global user.email 'action@github.com'
#           git add urls.txt pins/ data/
#           git commit -m "Process batch of URLs and save pins [skip ci]" || echo "No changes to commit"
#           git push
